### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by abdulrazzaqal-dulaimi** [ghufran-adel/Mini-GameProject#9]
The local storage on a live sever its not keeping truck for complex navigation when navigating links with different file path

**Comment by ghufran-adel** [comment]
paths has been fixed and pushed in the same branch of Abdul , the pull request have to be merged to the main after solving the conflict ..if you could please do that since you wrote the main code in that branch  @abdulrazzaqal-dulaimi

**Comment by abdulrazzaqal-dulaimi** [comment]
.
